version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my-company-crm
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
